"use client";

import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/ui/icon";
import { BillingCycle, formatMoney, monthlyPrice, subscriptionPlans } from "@/lib/subscription-plans";

const comparison = [
  ["Lượt phân tích / tháng", "20", "80"],
  ["Trang xử lý / tháng", "300", "1.500"],
  ["Thành viên, bao gồm Owner", "3", "10"],
  ["Giải thích và nguồn tham chiếu", "Có", "Có"],
  ["Xuất báo cáo rà soát", "Có", "Có"],
  ["Phân công Reviewer / Staff", "Không", "Có"],
  ["Lịch sử rà soát chung", "Không", "Có"],
];
const faqs = [
  ["Mỗi thành viên có cần mua gói riêng không?", "Không. Một gói áp dụng cho cả doanh nghiệp. Lượt phân tích và số trang được dùng chung; số thành viên đã bao gồm Organization Owner."],
  ["Hạn mức được tính như thế nào?", "Mỗi lần gửi một hợp đồng để phân tích là một lượt. Số trang được tính riêng; khi hết lượt hoặc hết số trang, cần nâng cấp hoặc chờ kỳ mới. Phân tích lại được tính là lượt mới. Đây là quy tắc minh họa của bản demo."],
  ["Gói năm có được nhận toàn bộ hạn mức ngay không?", "Không. Gói năm thanh toán một lần cho 12 tháng, nhưng hạn mức phân tích và số trang vẫn được cấp theo từng tháng. Hạn mức chưa dùng không cộng dồn trong phương án minh họa này."],
  ["Hết dùng thử thì dữ liệu có mất không?", "Thiết kế dự kiến cho phép xem kết quả cũ và chọn gói để tiếp tục phân tích. Chính sách lưu trữ chính thức sẽ được công bố trước khi mở bán."],
  ["Chọn gói ở đây có bị thu tiền không?", "Không. Đây là trải nghiệm minh họa. Bạn có thể xem giá và xác nhận lựa chọn demo; không có giao dịch, tự động gia hạn hay thay đổi tài khoản thật."],
];

export function SubscriptionCatalog() {
  const [cycle, setCycle] = useState<BillingCycle>("monthly");
  return <>
    <div className="mb-8 [&_h1]:text-[length:clamp(30px,3.4vw,46px)] [&_h1]:leading-[1.2] [&_h1]:tracking-[-1.7px] [&_h1]:font-bold [&_h1]:mt-0 [&_h1]:mb-[18px] [&_h1]:mx-0 [&_h1_span]:text-[color:var(--muted)] [&_h1_span]:font-[450] [&_h1_span]:[@media_(max-width:_580px)]:before:content-['_'] [&>_p]:last:text-[color:var(--muted)] [&>_p]:last:text-[length:15px] [&_h1]:[@media_(max-width:_580px)]:text-[length:32px] [&_h1]:[@media_(max-width:_580px)]:tracking-[-1px] [&>_p]:[@media_(max-width:_580px)]:last:text-[length:14px] [&_br]:[@media_(max-width:_580px)]:hidden"><p className="text-[color:var(--blue)] text-[length:10px] tracking-[1.5px] font-bold mb-3">ĐẦU TƯ CHO QUYẾT ĐỊNH RÕ RÀNG HƠN</p><h1>Một gói dịch vụ.<br /><span>Cả đội ngũ cùng sử dụng.</span></h1><p>Chọn không gian phù hợp để quản lý hợp đồng và phối hợp rà soát.<br />Hạn mức dùng chung, quyền lợi rõ ràng ngay từ đầu.</p></div>
    <section className="[background:var(--surface)] border border-[color:var(--line)] grid grid-cols-[1fr_1.2fr] gap-[30px] items-center px-7 py-6 rounded-[14px] border-solid [&_h2]:text-[length:20px] [&_h2]:font-[650] [&_h2]:flex [&_h2]:items-center [&_h2]:gap-3 [&_h2]:mt-[7px] [&_h2]:mb-1 [&_h2]:mx-0 [&_p]:text-[length:12px] [&_p]:text-[color:var(--muted)] [@media_(max-width:_800px)]:gap-[22px] [@media_(max-width:_580px)]:grid-cols-[1fr] [@media_(max-width:_580px)]:p-[22px]" aria-labelledby="trial-heading">
      <div><span className="text-[color:var(--muted)] text-[length:10px] font-[650] tracking-[1px]">GÓI HIỆN TẠI · DỮ LIỆU MẪU</span><h2 id="trial-heading">Dùng thử <span className="text-[color:var(--blue)] [background:var(--soft)] text-[length:10px] font-semibold px-[9px] py-1 rounded-md">Còn 4 ngày</span></h2><p>Trải nghiệm quy trình trước khi chọn gói.</p></div>
      <div className="grid gap-2 [&>_div_>_div]:flex [&>_div_>_div]:justify-between [&>_div_>_div]:text-[length:12px] [&>_div_>_div]:text-[color:var(--muted)] [&_strong]:text-[color:var(--ink)] [&_strong]:font-[550] [&_progress]:appearance-none [&_progress]:w-full [&_progress]:h-[5px] [&_progress]:block [&_progress]:[background:var(--soft)] [&_progress]:overflow-hidden [&_progress]:mt-1 [&_progress]:rounded-[10px] [&_progress]:border-0 [&_progress]:border-none [&_progress]:border-current [&_progress::-webkit-progress-bar]:[background:var(--soft)] [&_progress::-webkit-progress-value]:[background:var(--blue)] [&_progress::-webkit-progress-value]:rounded-[10px] [&_progress::-moz-progress-bar]:[background:var(--blue)]">{[["Lượt phân tích", 2, 3], ["Trang xử lý", 24, 100], ["Thành viên", 1, 2]].map(([label, value, max]) => <div key={label}><div><span>{label}</span><strong>{value}/{max}</strong></div><progress aria-label={`${label} đã dùng`} value={value} max={max} /></div>)}</div>
    </section>
    <div className="flex justify-between gap-5 items-center mt-10 mb-[22px] mx-0 [&_h2]:text-[length:20px] [&_h2]:font-[650] [&_p]:text-[length:12px] [&_p]:text-[color:var(--muted)] [&_p]:mt-[3px] [@media_(max-width:_1150px)]:items-start [@media_(max-width:_1150px)]:flex-col [@media_(max-width:_580px)]:mt-[30px]"><div><h2>Chọn cách đồng hành</h2><p>Giá và quyền lợi dự kiến, chưa mở bán.</p></div><fieldset className="[&_label]:cursor-pointer flex gap-[3px] border border-[color:var(--line)] [background:#edf0f5] shrink-0 p-1 rounded-[10px] border-solid [&_label]:text-[length:12px] [&_label]:flex [&_label]:items-center [&_label]:gap-[7px] [&_label]:text-[color:var(--muted)] [&_label]:relative [&_label]:px-3 [&_label]:py-[9px] [&_label]:rounded-[7px] [&_input]:absolute [&_input]:w-px [&_input]:h-px [&_input]:opacity-0 [&_label:has(input:focus-visible)]:[outline:3px_solid_var(--blue)] [&_label:has(input:focus-visible)]:outline-offset-[3px] [&_small]:text-[length:9px] [&_small]:text-[color:var(--blue)] [@media_(max-width:_580px)]:w-full [&_label]:[@media_(max-width:_580px)]:justify-center [&_label]:[@media_(max-width:_580px)]:flex-1 [&_label]:[@media_(max-width:_580px)]:[padding-inline:8px]"><legend className="absolute w-px h-px overflow-hidden [clip-path:inset(50%)] whitespace-nowrap">Chu kỳ thanh toán</legend>{(["monthly", "yearly"] as const).map(value => <label key={value} className={cycle === value ? "text-[color:var(--ink)] [background:var(--surface)] shadow-[0_2px_4px_#080e2f0a] font-semibold" : ""}><input type="radio" name="cycle" checked={cycle === value} onChange={() => setCycle(value)} /><span>{value === "monthly" ? "Hàng tháng" : "Hàng năm"}</span>{value === "yearly" && <small>Tiết kiệm hơn</small>}</label>)}</fieldset></div>
    <div className="grid grid-cols-[1fr_1fr] gap-[22px] [@media_(max-width:_580px)]:grid-cols-[1fr]">{subscriptionPlans.map(plan => <article className={`${"[background:var(--surface)] border border-[color:var(--line)] transition-shadow duration-200 ease-[ease] delay-0 p-7 rounded-2xl border-solid hover:shadow-[0_10px_28px_#1426460a] [&_h2]:text-[length:25px] [&_h2]:font-[650] [&_h2]:tracking-[-0.6px] [&>_p]:text-[color:var(--muted)] [&>_p]:text-[length:13px] [@media_(max-width:_1150px)]:p-[22px] [@media_(max-width:_580px)]:p-[26px]"} ${plan.id === "team" ? "border-[color:var(--blue)] [background:linear-gradient(160deg,#edf4ff,white_45%)]" : ""}`} key={plan.id}>
      <div className="flex justify-between items-center mb-5"><span className="inline-flex border [background:var(--soft)] text-[color:var(--blue)] p-2.5 rounded-xl border-solid border-[#dbe9ff]"><Icon name={plan.id === "team" ? "team" : "document"} /></span>{plan.id === "team" && <span className="text-[color:var(--blue)] [background:var(--soft)] text-[length:10px] font-semibold px-[9px] py-1 rounded-md">Dành cho đội ngũ</span>}</div>
      <h2>{plan.name}</h2><p>{plan.description}</p>
      <div className="flex gap-2 items-baseline mt-7 [&_strong]:text-[length:clamp(30px,3vw,40px)] [&_strong]:leading-[1.2] [&_strong]:font-[650] [&_strong]:tracking-[-1.5px] [&_strong]:[font-variant-numeric:tabular-nums] [&_span]:text-[color:var(--muted)] [&_span]:text-[length:13px] [&_strong]:[@media_(max-width:_580px)]:text-[length:38px]" aria-live="polite"><strong>{formatMoney(monthlyPrice(plan, cycle))}</strong><span>/ tháng</span></div>
      <p className="text-[length:12px] text-[color:var(--muted)] mt-2">{cycle === "yearly" ? `${formatMoney(monthlyPrice(plan, cycle) * 12)} / năm, thanh toán một lần.` : "Cho cả doanh nghiệp, thanh toán hàng tháng."}</p>
      <Link className={plan.id === "team" ? "w-full flex justify-center items-center gap-3 border border-[color:var(--blue)] min-h-12 text-[length:14px] font-semibold transition-[background] duration-200 ease-[ease] delay-0 mt-6 px-4 py-3 rounded-lg border-solid [background:var(--blue)] text-[white] [&:not(:disabled)]:hover:[background:#0056d9]" : "w-full flex justify-center items-center gap-3 border border-[color:var(--blue)] min-h-12 text-[length:14px] font-semibold transition-[background] duration-200 ease-[ease] delay-0 mt-6 px-4 py-3 rounded-lg border-solid text-[color:var(--ink)] [background:var(--surface)] border-[color:var(--line)] hover:[background:var(--soft)]"} href={`/goi-dich-vu/xac-nhan?plan=${plan.id}&cycle=${cycle}`}>Chọn gói {plan.name}<Icon name="arrow" width={18} height={18} /></Link>
      <div className="grid grid-cols-[repeat(3,1fr)] gap-[5px] [border-bottom:1px_solid_var(--line)] mb-[22px] px-0 py-[22px] [&>_div]:grid [&>_div]:gap-0.5 [&_strong]:text-[length:20px] [&_strong]:font-[650] [&_span]:text-[length:10px] [&_span]:text-[color:var(--muted)]"><div><strong>{plan.reviews}</strong><span>lượt / tháng</span></div><div><strong>{plan.pages.toLocaleString("vi-VN")}</strong><span>trang / tháng</span></div><div><strong>{plan.members}</strong><span>thành viên</span></div></div>
      <ul>{plan.features.map(feature => <li key={feature}><Icon name="check" width={18} height={18} />{feature}</li>)}</ul>
      <p className="text-[length:11px] [border-top:1px_solid_var(--line)] mt-6 pt-4">Số thành viên bao gồm Owner. Dừng phân tích khi hết lượt hoặc số trang.</p>
    </article>)}</div>
    <p className="text-center text-[length:11px] text-[color:var(--muted)] mt-[18px]">Giá minh họa bằng VNĐ. Thuế và chính sách thanh toán sẽ được công bố khi mở bán.</p>
    <section className="mt-[60px] [&_h2]:text-[length:26px] [&_h2]:font-[650] [&_h2]:tracking-[-0.8px] [&>_p]:text-[color:var(--muted)] [&>_p]:text-[length:13px] [&>_p]:mt-1.5 [@media_(max-width:_580px)]:mt-10" aria-labelledby="comparison-heading"><h2 id="comparison-heading">Đúng nhu cầu, rõ quyền lợi.</h2><p>Đối chiếu những gì đội ngũ của bạn cần mỗi ngày.</p><div className="overflow-x-auto border border-[color:var(--line)] [background:var(--surface)] mt-6 rounded-xl border-solid [&_table]:w-full [&_table]:text-[length:13px] [&_table]:min-w-[440px] [&_table]:border-collapse [&_th]:[border-bottom:1px_solid_var(--line)] [&_th]:text-center [&_th]:px-[22px] [&_th]:py-[15px] [&_td]:[border-bottom:1px_solid_var(--line)] [&_td]:text-center [&_td]:px-[22px] [&_td]:py-[15px] [&_tr:last-child_>_*]:[border-bottom:0] [&_th]:first:text-left [&_th]:first:w-[52%] [&_thead]:[background:#f0f5fc] [&_tbody_th]:font-[450] [&_td]:last:text-[color:var(--blue)] [&_th]:[@media_(max-width:_580px)]:p-3.5 [&_td]:[@media_(max-width:_580px)]:p-3.5" tabIndex={0} role="region" aria-label="Bảng so sánh gói có thể cuộn ngang"><table><caption className="absolute w-px h-px overflow-hidden [clip-path:inset(50%)] whitespace-nowrap">So sánh gói Cơ bản và Nhóm</caption><thead><tr><th scope="col">Quyền lợi</th><th scope="col">Cơ bản</th><th scope="col">Nhóm</th></tr></thead><tbody>{comparison.map(([label, basic, team]) => <tr key={label}><th scope="row">{label}</th><td>{basic}</td><td>{team}</td></tr>)}</tbody></table></div></section>
    <section className="[&_h2]:text-[length:26px] [&_h2]:font-[650] [&_h2]:tracking-[-0.8px] [&>_div_>_p:last-child]:text-[color:var(--muted)] [&>_div_>_p:last-child]:text-[length:13px] [&>_div_>_p:last-child]:mt-1.5 grid grid-cols-[1fr_1.7fr] gap-10 mt-[60px] [&_details]:[border-bottom:1px_solid_var(--line)] [&_summary]:flex [&_summary]:items-center [&_summary]:justify-between [&_summary]:gap-4 [&_summary]:[list-style:none] [&_summary]:text-[length:13px] [&_summary]:font-[550] [&_summary]:px-0 [&_summary]:py-[18px] [&_summary::-webkit-details-marker]:hidden [&_summary_span]:text-[color:var(--blue)] [&_summary_span]:text-[length:20px] [&_details[open]_summary_span]:[transform:rotate(45deg)] [&_details_p]:text-[color:var(--muted)] [&_details_p]:text-[length:13px] [&_details_p]:pb-5 [@media_(max-width:_580px)]:grid-cols-[1fr] [@media_(max-width:_580px)]:gap-5 [@media_(max-width:_580px)]:mt-10" aria-labelledby="faq-heading"><div><p className="text-[color:var(--blue)] text-[length:10px] tracking-[1.5px] font-bold mb-3">TRƯỚC KHI BẠN CHỌN</p><h2 id="faq-heading">Một vài điều<br />cần làm rõ.</h2><p>Để bạn biết mình sẽ nhận được gì.</p></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
  </>;
}
