"use client";

import { useState } from "react";
import Link from "next/link";
import { Icon } from "@/components/ui/icon";
import { BillingCycle, demoOrganization, formatMoney, monthlyPrice, SubscriptionPlan } from "@/lib/subscription-plans";

export function SubscriptionConfirmation({ plan, cycle }: { plan: SubscriptionPlan; cycle: BillingCycle }) {
  const [confirmed, setConfirmed] = useState(false);
  const total = monthlyPrice(plan, cycle) * (cycle === "yearly" ? 12 : 1);
  return <>
    <Link className="inline-block text-[color:var(--muted)] text-[length:13px] mb-[30px]" href="/goi-dich-vu">← Quay lại gói dịch vụ</Link>
    <div className="mb-8 [&_h1]:text-[length:clamp(30px,3.4vw,46px)] [&_h1]:leading-[1.2] [&_h1]:tracking-[-1.7px] [&_h1]:font-bold [&_h1]:mt-0 [&_h1]:mb-[18px] [&_h1]:mx-0 [&_h1_span]:text-[color:var(--muted)] [&_h1_span]:font-[450] [&_h1_span]:[@media_(max-width:_580px)]:before:content-['_'] [&>_p]:last:text-[color:var(--muted)] [&>_p]:last:text-[length:15px] [&_h1]:[@media_(max-width:_580px)]:text-[length:32px] [&_h1]:[@media_(max-width:_580px)]:tracking-[-1px] [&>_p]:[@media_(max-width:_580px)]:last:text-[length:14px] [&_br]:[@media_(max-width:_580px)]:hidden"><p className="text-[color:var(--blue)] text-[length:10px] tracking-[1.5px] font-bold mb-3">LỰA CHỌN CỦA DOANH NGHIỆP</p><h1>Xem lại trước khi<br /><span>bạn quyết định.</span></h1><p>Mọi quyền lợi và chi phí trong một bản tóm tắt.</p></div>
    <div className="grid grid-cols-[1.15fr_1fr] gap-6 [align-items:start] [@media_(max-width:_1150px)]:grid-cols-[1fr] [&_h2]:text-[length:23px] [&_h2]:font-[650] [&_h2]:mt-3 [&_h3]:text-[length:20px] [&_h3]:font-semibold [&_hr]:[border-top:1px_solid_var(--line)] [&_hr]:mx-0 [&_hr]:my-7 [&_hr]:border-0 [&_hr]:border-none [&_hr]:border-current">
      <section className="[background:var(--surface)] border border-[color:var(--line)] p-[30px] rounded-2xl border-solid [&>_p]:text-[color:var(--muted)] [&>_p]:text-[length:13px] [&>_p]:mt-[5px] [&>_p]:mb-5 [&>_p]:mx-0 [@media_(max-width:_580px)]:p-[23px]"><span className="inline-flex border [background:var(--soft)] text-[color:var(--blue)] p-2.5 rounded-xl border-solid border-[#dbe9ff]"><Icon name="building" /></span><h2>{demoOrganization}</h2><p>Doanh nghiệp mẫu · Organization Owner</p><hr /><h3>LawScan {plan.name}</h3><p>{plan.description}</p><ul>{[`${plan.reviews} lượt phân tích và ${plan.pages.toLocaleString("vi-VN")} trang mỗi tháng`, `${plan.members} thành viên, bao gồm Owner`, ...plan.features].map(feature => <li key={feature}><Icon name="check" width={18} height={18} />{feature}</li>)}</ul><div className="flex gap-2.5 items-start [background:var(--soft)] text-[color:var(--muted)] text-[length:12px] mt-[26px] p-4 rounded-[10px] [&_svg]:text-[color:var(--blue)] [&_svg]:w-[18px] [&_svg]:shrink-0"><Icon name="shield" /><p>Hạn mức dùng chung trong doanh nghiệp. Gói năm vẫn cấp hạn mức theo từng tháng; hết lượt hoặc số trang sẽ dừng phân tích mới.</p></div></section>
      <section className="[background:var(--surface)] border border-[color:var(--line)] p-[30px] rounded-2xl border-solid [&_dl]:mt-6 [&_dl_>_div]:flex [&_dl_>_div]:justify-between [&_dl_>_div]:gap-3 [&_dl_>_div]:text-[length:13px] [&_dl_>_div]:mt-[15px] [&_dt]:text-[color:var(--muted)] [&_dd]:text-right [&_dd]:font-[550] [@media_(max-width:_580px)]:p-[23px]"><span className="text-[color:var(--muted)] text-[length:10px] font-[650] tracking-[1px]">TÓM TẮT LỰA CHỌN</span><h2>Gói {plan.name}</h2><dl><div><dt>Chu kỳ</dt><dd>{cycle === "yearly" ? "Hàng năm" : "Hàng tháng"}</dd></div><div><dt>Giá mỗi tháng</dt><dd>{formatMoney(monthlyPrice(plan, cycle))}</dd></div>{cycle === "yearly" && <div><dt>Tiết kiệm mỗi năm</dt><dd>{formatMoney((plan.monthly - plan.annualMonthly) * 12)}</dd></div>}<div className="[border-top:1px_solid_var(--line)] items-center mt-6 pt-6 [&_dd]:text-[length:27px] [&_dd]:tracking-[-1px] [&_small]:block [&_small]:text-[color:var(--muted)] [&_small]:text-[length:12px] [&_small]:font-normal [&_small]:tracking-[normal]"><dt>Tổng tiền minh họa</dt><dd>{formatMoney(total)}<small>/ {cycle === "yearly" ? "năm" : "tháng"}</small></dd></div></dl><p className="text-[length:12px] text-[color:var(--muted)] mt-2">Thuế và chính sách thanh toán chưa áp dụng trong bản demo.</p>
        <div className="flex gap-2.5 items-start [background:var(--soft)] text-[color:var(--muted)] text-[length:12px] mt-[26px] p-4 rounded-[10px] [&_svg]:text-[color:var(--blue)] [&_svg]:w-[18px] [&_svg]:shrink-0"><Icon name="lock" /><p>Đây là bản mô phỏng. Không thu tiền, không kích hoạt gói và không tự động gia hạn.</p></div>
        <button className="w-full flex justify-center items-center gap-3 border border-[color:var(--blue)] min-h-12 text-[length:14px] font-semibold transition-[background] duration-200 ease-[ease] delay-0 mt-6 px-4 py-3 rounded-lg border-solid [background:var(--blue)] text-[white] [&:not(:disabled)]:hover:[background:#0056d9]" onClick={() => setConfirmed(true)} disabled={confirmed}>{confirmed ? "Đã xác nhận lựa chọn demo" : "Xác nhận lựa chọn demo"}<Icon name={confirmed ? "check" : "arrow"} width={18} height={18} /></button>
        <div role="status" aria-live="polite">{confirmed && <p className="[background:var(--soft)] text-[color:var(--ink)] [border-left:3px_solid_var(--blue)] text-[length:13px] mt-4 p-3.5">Bạn đã chọn gói {plan.name} theo {cycle === "yearly" ? "năm" : "tháng"} trong bản demo. Lựa chọn chỉ tồn tại trên màn hình này, chưa lưu vào tài khoản.</p>}</div>
        <Link className="block text-center text-[color:var(--muted)] text-[length:13px] mt-[18px]" href="/goi-dich-vu">Chọn gói khác</Link>
      </section>
    </div>
  </>;
}
