import { Icon } from "@/components/ui/icon";

const events = [
  { title: "Cần chỉnh sửa", date: "10 thg 3, 09:15", description: "Một số điều khoản cần làm rõ về thời hạn và nghiệm thu.", color: "amber" },
  { title: "Đã cập nhật", date: "11 thg 3, 14:20", description: "Đã chỉnh sửa theo góp ý của đội ngũ.", color: "blue" },
  { title: "Hoàn tất rà soát", date: "12 thg 3, 16:05", description: "Đã bổ sung điều kiện nghiệm thu.", color: "green" },
];

export function CollaborationSection() {
  return (
    <section id="phoi-hop" className="relative grid-cols-[1fr_1fr] gap-[50px] min-h-[465px] [background:radial-gradient(ellipse_at_38%_30%,#1c2d47,#0e1b32_74%)] text-[white] isolate overflow-hidden px-[50px] py-[35px] rounded-[18px] [&_h2]:text-[length:clamp(36px,3.8vw,54px)] [&_h2]:font-bold [&_h2]:leading-[1.12] [&_h2]:tracking-[-1.7px] [@media_(max-width:_1199px)]:gap-[25px] [@media_(max-width:_1199px)]:p-8 [@media_(max-width:_900px)]:grid-cols-[1fr] [@media_(max-width:_900px)]:p-9 [@media_(max-width:_600px)]:gap-[30px] [@media_(max-width:_600px)]:px-5 [@media_(max-width:_600px)]:py-7 [@media_(max-width:_600px)]:rounded-[13px] [&_h2]:[@media_(max-width:_600px)]:text-[length:36px] w-[min(1380px,calc(100%_-_112px))] [margin-inline:auto] [@media_(max-width:_1199px)]:w-[calc(100%_-_64px)] [@media_(max-width:_600px)]:w-[calc(100%_-_40px)] grid items-center" aria-labelledby="collaboration-heading">
      <svg className="absolute w-full h-full z-[-1] inset-0" viewBox="0 0 1200 460" preserveAspectRatio="none" fill="none" aria-hidden="true"><path d="M0 470C180 280 600 430 510 195S650 5 860 80" stroke="#0875ff" strokeWidth="1.5" /></svg>
      <div className="collaboration-copy"><p className="flex gap-[11px] items-center text-[#7382a5] text-[length:11px] font-semibold uppercase tracking-[1.8px] mb-4 before:content-[''] before:w-5 before:h-0.5 before:[background:var(--ls-blue)] text-[#bbc7db] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:tracking-[1.2px]">03 / AI hỗ trợ phân tích</p><h2 id="collaboration-heading">AI phân tích.<br />Bạn quyết định.</h2><p>Cùng rà soát, thảo luận và thống nhất cách xử lý,<br className="hidden xl:block" /> mọi bước đều được ghi nhận rõ ràng.</p><a href="#quy-trinh" className="inline-flex items-center gap-[17px] [border-bottom:2px_solid_var(--ls-blue)] mt-[22px] pb-1.5 hover:text-[#80b8ff] [@media_(max-width:_600px)]:text-[length:14px]">Khám phá quy trình <Icon name="arrow" /></a><span className="block text-[#89b6e7] [font-family:'Segoe_Print','Comic_Sans_MS',cursive] italic text-[length:19px] leading-tight [transform:rotate(-8deg)] text-center ml-20 mr-0 mt-11 -mb-2 [@media_(max-width:_900px)]:hidden">Từ điều khoản<br />đến quyết định tốt hơn.</span></div>
      <div className="relative pr-[58px] [@media_(max-width:_1199px)]:pr-[25px] [@media_(max-width:_900px)]:max-w-[480px] [@media_(max-width:_900px)]:w-full [@media_(max-width:_900px)]:mt-3.5 [@media_(max-width:_900px)]:mb-2.5 [@media_(max-width:_900px)]:mx-auto [@media_(max-width:_600px)]:pr-3">
        <div className="absolute w-4/5 h-[88%] [transform:rotate(12deg)] [background:repeating-linear-gradient(0deg,#e6eaf0_0px,#e6eaf0_5px,#f6f7f8_5px,#f6f7f8_12px)] shadow-[0_10px_20px_#0003] border-[23px] border-solid border-[#f8f9fb] right-[25px] top-[22px] [@media_(max-width:_600px)]:border-[12px] [@media_(max-width:_600px)]:right-0 sheet-one" aria-hidden="true" /><div className="absolute w-4/5 h-[88%] [transform:rotate(12deg)] [background:repeating-linear-gradient(0deg,#e6eaf0_0px,#e6eaf0_5px,#f6f7f8_5px,#f6f7f8_12px)] shadow-[0_10px_20px_#0003] border-[23px] border-solid border-[#f8f9fb] right-[25px] top-[22px] [@media_(max-width:_600px)]:border-[12px] [@media_(max-width:_600px)]:right-0 [transform:rotate(22deg)] z-[-1] h-[78%] right-1.5 top-12 [@media_(max-width:_600px)]:hidden" aria-hidden="true" />
        <article className="relative z-[2] [background:#fff] text-[color:var(--ls-ink)] border shadow-[0_15px_30px_#0002] [transform:rotate(-0.3deg)] text-[length:12px] p-6 rounded-[13px] border-solid border-[#d6dce6] [&_p]:text-[color:var(--ls-muted)] [&_h4]:text-[length:14px] [&_h4]:font-semibold [&_h4]:mt-5 [&_h4]:mb-[7px] [&_h4]:mx-0 [@media_(max-width:_1199px)]:p-[18px] [@media_(max-width:_900px)]:p-6 [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:p-[15px] [&_h4]:[@media_(max-width:_600px)]:text-[length:12px]" aria-label="Minh họa ghi nhận rà soát hợp đồng">
          <div className="[&_h3]:text-[length:14px] [&_h3]:font-bold relative [&_h3]:[@media_(max-width:_600px)]:text-[length:11px] flex items-start gap-3"><span className="grid place-items-center [background:#e6f1ff] text-[color:var(--ls-blue)] p-2.5 rounded-[10px] [@media_(max-width:_600px)]:p-[7px]"><Icon name="document" /></span><div><p className="text-[length:9px] uppercase tracking-[1.4px] font-bold mb-[9px] [@media_(max-width:_600px)]:text-[length:7px]">Ghi nhận rà soát</p><h3>Rà soát hợp đồng dịch vụ</h3><p>Tạo ngày 10 thg 3, 2026</p></div><span className="[align-self:start] whitespace-nowrap text-[length:10px] text-[color:var(--ls-blue)] [background:#e8f2ff] ml-auto px-[9px] py-1.5 rounded-[25px] [@media_(max-width:_1199px)]:hidden [@media_(max-width:_900px)]:block [@media_(max-width:_600px)]:hidden">Minh họa</span></div>
          <h4>Người phụ trách</h4><div className="[border-bottom:1px_solid_#e3e7ee] pb-4 flex items-center gap-3"><span className="[background:#dfe5ef] w-[42px] h-[42px] grid place-items-center text-[length:16px] rounded-[50%]">NT</span><div><strong>Nguyễn Thị An</strong><p>Phòng pháp chế</p></div></div>
          <ol className="mt-4 [&_li]:grid [&_li]:relative [&_li]:grid-cols-[17px_1fr_1.18fr] [&_li]:gap-[13px] [&_li]:pb-[21px] [&_li]:last:pb-0 [&_li:not(:last-child)]:before:content-[''] [&_li:not(:last-child)]:before:absolute [&_li:not(:last-child)]:before:w-0.5 [&_li:not(:last-child)]:before:[background:#e0e5ed] [&_li:not(:last-child)]:before:bottom-[-5px] [&_li:not(:last-child)]:before:left-[7px] [&_li:not(:last-child)]:before:top-2.5 [&_li]:[@media_(max-width:_600px)]:gap-2 [&_li]:[@media_(max-width:_600px)]:grid-cols-[16px_1fr_1fr]">{events.map(event => <li key={event.title}><span className={`timeline-dot ${event.color}`} /><div><strong>{event.title}</strong><p>{event.date}</p></div><p>{event.description}</p></li>)}</ol>
        </article>
        <span className="absolute right-[-34px] z-[3] text-[length:17px] -bottom-3.5 [@media_(max-width:_600px)]:hidden block text-[#89b6e7] [font-family:'Segoe_Print','Comic_Sans_MS',cursive] italic text-[length:19px] leading-tight [transform:rotate(-8deg)] text-center ml-20 mr-0 mt-11 -mb-2 [@media_(max-width:_900px)]:hidden">Rõ ràng<br />hơn mỗi ngày</span>
      </div>
    </section>
  );
}
