"use client";

import { useEffect, useRef, useState } from "react";
import { Brand } from "@/components/ui/brand";
import { Icon } from "@/components/ui/icon";

const examples = [
  { label: "Thanh toán", title: "Điều 2. Thanh toán", prefix: "Bên A thanh toán", clause: "sau khi hoàn thành dịch vụ.", risk: "Thời hạn chưa cụ thể", detail: "Cần làm rõ thời điểm thanh toán.", suggestion: "Bổ sung số ngày và điều kiện thanh toán." },
  { label: "Nghiệm thu", title: "Điều 2. Nghiệm thu", prefix: "Dịch vụ được nghiệm thu", clause: "khi đạt yêu cầu của Bên A.", risk: "Tiêu chí chưa rõ ràng", detail: "Cần thống nhất tiêu chí nghiệm thu.", suggestion: "Bổ sung tiêu chí, thời hạn và biên bản nghiệm thu." },
  { label: "Chấm dứt", title: "Điều 2. Chấm dứt", prefix: "Một bên được chấm dứt", clause: "bất cứ khi nào cần thiết.", risk: "Điều kiện chưa cụ thể", detail: "Cần làm rõ nghĩa vụ thông báo.", suggestion: "Làm rõ điều kiện, thời gian báo trước và nghĩa vụ còn lại." },
];

export function ContractDemo() {
  const [selected, setSelected] = useState(0);
  const stageRef = useRef<HTMLDivElement>(null);
  const example = examples[selected];

  useEffect(() => {
    const stage = stageRef.current;
    if (!stage || !("IntersectionObserver" in window)) return;

    // Start the one-shot illustration only when it is visible, including on mobile.
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) {
        stage.dataset.demoReady = "true";
        observer.disconnect();
      }
    }, { threshold: 0.15 });
    observer.observe(stage);
    return () => observer.disconnect();
  }, []);

  return (
    <div id="minh-hoa" className="min-w-0">
      <div ref={stageRef} className="relative h-[clamp(450px,41vw,615px)] overflow-hidden bg-[#edf4fc70] bg-[radial-gradient(ellipse_at_66%_42%,#c4ddff80_0,transparent_65%),linear-gradient(#a6c1de1a_1px,transparent_1px),linear-gradient(90deg,#a6c1de1a_1px,transparent_1px)] bg-[length:auto,62px_62px,62px_62px] border shadow-[inset_0_0_60px_#fff4,0_24px_70px_-50px_#0047a550] isolate rounded-3xl border-solid border-[#ffffff70] motion-safe:data-[demo-ready]:animate-[ls-stage-bounce_4.6s_ease-in-out_infinite] motion-safe:data-[demo-ready]:will-change-transform [@media_(max-width:_900px)]:h-[570px] [@media_(max-width:_600px)]:h-[380px] [@media_(max-width:_600px)]:rounded-2xl" id="clause-preview" aria-live="polite" aria-atomic="true">
        <div className="absolute text-[#d6e5f5] text-[length:740px] leading-none right-[-38px] top-[-53px] z-[-1] [@media_(max-width:_600px)]:text-[length:450px] [@media_(max-width:_600px)]:top-[-30px]" aria-hidden="true">↗</div>
        <article className="absolute w-[71%] h-[94%] [background:linear-gradient(115deg,#fff,#f8f9fb)] border shadow-[0_3px_6px_#21395514,0_22px_35px_#21395530,16px_35px_65px_-25px_#1e457b40] [transform:rotate(-5deg)] px-[5%] py-[7%] border-solid border-white left-[13%] top-[4%] motion-safe:animate-[ls-paper-hop_5.2s_ease-in-out_0.45s_infinite] [@media_(max-width:_600px)]:w-[82%] [@media_(max-width:_600px)]:h-[91%] [@media_(max-width:_600px)]:px-5 [@media_(max-width:_600px)]:py-[25px] [@media_(max-width:_600px)]:left-[8%] [@media_(max-width:_600px)]:top-[5%]">
          <div className="flex items-center gap-4 [border-bottom:1px_solid_#dce0e8] pb-[26px] [&_strong]:text-[length:clamp(15px,1.65vw,24px)] [&_strong]:whitespace-nowrap [&_strong]:tracking-[-0.6px] [&_small]:text-[color:var(--ls-muted)] [&_small]:text-[length:12px] [&_small]:whitespace-nowrap [&_small]:ml-auto [@media_(max-width:_1199px)]:gap-2 [&_small]:[@media_(max-width:_1199px)]:hidden [&_strong]:[@media_(max-width:_900px)]:text-[length:24px] [@media_(max-width:_900px)]:gap-3.5 [@media_(max-width:_600px)]:gap-[9px] [@media_(max-width:_600px)]:pb-[18px] [&_strong]:[@media_(max-width:_600px)]:text-[length:14px]"><Brand markOnly /><strong>HỢP ĐỒNG DỊCH VỤ</strong><small>LS · 2026</small></div>
          <div className="text-[#66708b] text-[length:14px] mt-7 [@media_(max-width:_1199px)]:text-[length:12px] [@media_(max-width:_900px)]:text-[length:15px] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:mt-5"><b>Điều 1. Phạm vi công việc</b><div className="grid gap-[9px] mt-2.5 [&_i]:block [&_i]:h-2 [&_i]:[background:#e0e3e9] [&_i]:rounded-sm [&_i:nth-child(2)]:w-[94%] [&_i:nth-child(3)]:w-[65%] [&_i:nth-child(4)]:w-[85%] [@media_(max-width:_600px)]:gap-1.5 [&_i]:[@media_(max-width:_600px)]:h-[5px]" aria-hidden="true"><i /><i /><i /></div></div>
          <div key={`clause-${selected}`} className="mt-8 [&_h2]:text-[length:19px] [&_h2]:font-bold [&_h2]:mb-2.5 [&_p]:text-[length:16px] [&_p]:leading-loose [&_mark]:[background:#ffedc5] [&_mark]:text-[color:var(--ls-ink)] [&_mark]:box-decoration-clone [&_mark]:[-webkit-box-decoration-break:clone] [&_mark]:[border-inline:3px_solid_#0875ff] [&_mark]:px-1.5 [&_mark]:py-[5px] [&_mark]:rounded-[3px] motion-safe:animate-[ls-clause-in_0.35s_ease-out_both] [&_mark]:motion-safe:animate-[ls-highlight_0.45s_ease-out_0.55s_both] [&_p]:[@media_(max-width:_1199px)]:text-[length:13px] [&_p]:[@media_(max-width:_900px)]:text-[length:17px] [@media_(max-width:_600px)]:mt-[25px] [&_h2]:[@media_(max-width:_600px)]:text-[length:14px] [&_h2]:[@media_(max-width:_600px)]:mb-1.5 [&_p]:[@media_(max-width:_600px)]:text-[length:11px]"><h2>{example.title}</h2><p>{example.prefix} <mark>{example.clause}</mark></p></div>
          <div className="text-[#66708b] text-[length:14px] mt-7 [@media_(max-width:_1199px)]:text-[length:12px] [@media_(max-width:_900px)]:text-[length:15px] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:mt-5"><b>Điều 3. Quyền và nghĩa vụ của các bên</b><div className="grid gap-[9px] mt-2.5 [&_i]:block [&_i]:h-2 [&_i]:[background:#e0e3e9] [&_i]:rounded-sm [&_i:nth-child(2)]:w-[94%] [&_i:nth-child(3)]:w-[65%] [&_i:nth-child(4)]:w-[85%] [@media_(max-width:_600px)]:gap-1.5 [&_i]:[@media_(max-width:_600px)]:h-[5px]" aria-hidden="true"><i /><i /><i /><i /></div></div>
          <div className="absolute overflow-hidden pointer-events-none inset-0" aria-hidden="true"><div key={`scan-${selected}`} className="absolute h-[70%] opacity-0 [background:linear-gradient(transparent_65%,#1677ff05_80%,#1677ff20)] [border-bottom:2px_solid_#4c9aff] shadow-[0_6px_18px_-8px_#0875ff] top-0 bottom-auto inset-x-0 motion-safe:animate-[ls-scan_1.5s_cubic-bezier(.2,0.65,0.4,1)_both]" /></div>
        </article>
        <svg key={`line-${selected}`} className="absolute w-[13%] h-1/5 right-[27%] top-[36%] [&_path]:motion-safe:animate-[ls-connect_0.45s_ease-out_0.75s_both] [@media_(max-width:_600px)]:right-[37%] [@media_(max-width:_600px)]:top-[34%]" viewBox="0 0 120 120" fill="none" aria-hidden="true"><path pathLength="1" d="M5 112C48 112 26 12 111 12" stroke="#0066ff" strokeWidth="3" /><circle cx="5" cy="112" r="5" fill="#0066ff" /><circle cx="111" cy="12" r="5" fill="#0066ff" /></svg>
        <div key={`risk-${selected}`} className="absolute w-[31%] flex gap-2.5 border [background:#fffffffa] shadow-[0_3px_8px_#1b386a0d,0_20px_40px_-10px_#1b386a38] text-[length:14px] px-4 py-[19px] rounded-[14px] border-solid border-[#80aaff] right-[2.5%] top-[31%] [&_strong]:text-[length:15px] [&_strong]:tracking-[-0.3px] [&_p]:text-[#354260] [&_p]:mt-1.5 motion-safe:animate-[ls-note-in_0.5s_cubic-bezier(.22,1,0.36,1)_0.85s_both,ls-note-hop_4.9s_ease-in-out_1.45s_infinite] [@media_(max-width:_1199px)]:w-[34%] [@media_(max-width:_1199px)]:p-3 [&_strong]:[@media_(max-width:_1199px)]:text-[length:12px] [&_p]:[@media_(max-width:_1199px)]:text-[length:11px] [@media_(max-width:_900px)]:w-[29%] [&_strong]:[@media_(max-width:_900px)]:text-[length:14px] [&_p]:[@media_(max-width:_900px)]:text-[length:14px] [@media_(max-width:_600px)]:w-[42%] [@media_(max-width:_600px)]:gap-[5px] [@media_(max-width:_600px)]:p-[9px] [@media_(max-width:_600px)]:rounded-lg [@media_(max-width:_600px)]:right-[2%] [@media_(max-width:_600px)]:top-[27%] [&_strong]:[@media_(max-width:_600px)]:text-[length:10px] [&_p]:[@media_(max-width:_600px)]:text-[length:10px] [&_p]:[@media_(max-width:_600px)]:mt-[3px]"><span className="inline-flex shrink-0 justify-center items-center w-4 h-4 text-[white] text-[length:12px] [background:#ffb400] mt-1 rounded-[50%] border-2 border-solid border-[#ffe097] [@media_(max-width:_600px)]:w-2.5 [@media_(max-width:_600px)]:h-2.5 [@media_(max-width:_600px)]:w-[13px] [@media_(max-width:_600px)]:h-[13px] [@media_(max-width:_600px)]:text-[length:9px]" /><div><strong>{example.risk}</strong><p>{example.detail}</p></div></div>
        <div key={`suggestion-${selected}`} className="absolute w-[58%] flex gap-[13px] border [background:#fffffffa] shadow-[0_3px_8px_#17375c0a,0_24px_42px_-12px_#17375c38] p-5 rounded-[14px] border-solid border-[#c1d7f5] right-[7%] bottom-[11%] [&>_svg]:text-[color:var(--ls-blue)] [&>_svg]:shrink-0 [&>_svg]:fill-[var(--ls-blue)] [&_strong]:text-[color:var(--ls-blue)] [&_strong]:uppercase [&_strong]:text-[length:13px] [&_p]:text-[length:14px] [&_p]:mt-1.5 motion-safe:animate-[ls-note-in_0.6s_cubic-bezier(.22,1,0.36,1)_1.05s_both,ls-note-hop_5.4s_ease-in-out_2.05s_infinite_reverse] [@media_(max-width:_1199px)]:w-[65%] [@media_(max-width:_1199px)]:p-3.5 [@media_(max-width:_1199px)]:right-[5%] [@media_(max-width:_1199px)]:bottom-[8%] [&_p]:[@media_(max-width:_1199px)]:text-[length:12px] [&_p]:[@media_(max-width:_900px)]:text-[length:14px] [@media_(max-width:_900px)]:w-[56%] [@media_(max-width:_900px)]:bottom-[11%] [@media_(max-width:_600px)]:w-[77%] [@media_(max-width:_600px)]:gap-[9px] [@media_(max-width:_600px)]:p-3 [@media_(max-width:_600px)]:rounded-[9px] [@media_(max-width:_600px)]:right-[4%] [@media_(max-width:_600px)]:bottom-[7%] [&_strong]:[@media_(max-width:_600px)]:text-[length:10px] [&_p]:[@media_(max-width:_600px)]:text-[length:11px] [&_p]:[@media_(max-width:_600px)]:mt-[3px] [&>_svg]:[@media_(max-width:_600px)]:w-[19px]"><Icon name="sparkle" /><div><strong>Gợi ý làm rõ</strong><p>{example.suggestion}</p></div></div>
        <div className="absolute [transform:rotate(-35deg)] left-[6%] top-[44%] [&_i]:inline-block [&_i]:h-[38px] [&_i]:w-1 [&_i]:[background:var(--ls-blue)] [&_i]:ml-[15px] [&_i]:rounded-lg [&_i]:first:h-7 [&_i]:first:[transform:rotate(-20deg)] [@media_(max-width:_600px)]:hidden" aria-hidden="true"><i /><i /></div>
      </div>
      <div className="pl-[16%] pr-2 pt-5 pb-0 [@media_(max-width:_1199px)]:pl-0 [@media_(max-width:_900px)]:pl-[12%] [@media_(max-width:_600px)]:gap-2.5 [@media_(max-width:_600px)]:pt-3.5 [@media_(max-width:_600px)]:pb-0 [@media_(max-width:_600px)]:px-0 flex flex-wrap items-center justify-between gap-4">
        <div className="[&_button]:min-h-11 [&_button]:border [&_button]:text-[length:13px] [&_button]:whitespace-nowrap [&_button]:px-[18px] [&_button]:py-2.5 [&_button]:rounded-[15px] [&_button]:border-solid [&_button]:border-[#d5e1f0] [&_button]:hover:[background:#e9f2ff] [&_button]:aria-pressed:[background:var(--ls-blue)] [&_button]:aria-pressed:border-[color:var(--ls-blue)] [&_button]:aria-pressed:text-[white] [@media_(max-width:_600px)]:w-full [@media_(max-width:_600px)]:justify-between [@media_(max-width:_600px)]:gap-1.5 [&_button]:[@media_(max-width:_600px)]:flex-1 [&_button]:[@media_(max-width:_600px)]:text-[length:11px] [&_button]:[@media_(max-width:_600px)]:px-2 [&_button]:[@media_(max-width:_600px)]:py-[9px] [&_button]:[@media_(max-width:_600px)]:rounded-xl flex gap-2" role="group" aria-label="Chọn điều khoản minh họa">
          {examples.map((item, index) => <button type="button" key={item.label} aria-pressed={selected === index} aria-controls="clause-preview" onClick={() => setSelected(index)}>{item.label}</button>)}
        </div>
        <a href="#tinh-nang" className="inline-flex items-center gap-2 text-[length:12px] [@media_(max-width:_600px)]:text-[length:11px] [@media_(max-width:_600px)]:ml-auto">Ví dụ minh họa <Icon name="arrow" width="17" /></a>
      </div>
    </div>
  );
}
