const questions = [
  { question: "Hỗ trợ loại hợp đồng nào?", answer: "Mua bán hàng hóa và cung cấp dịch vụ thông thường bằng tiếng Việt." },
  { question: "Có đọc được PDF scan không?", answer: "PDF scan cần được nhận dạng ký tự (OCR) để trích xuất văn bản. Khả năng đọc phụ thuộc chất lượng bản quét; bạn cần kiểm tra lại nội dung được trích xuất." },
  { question: "Kết quả AI có cần kiểm tra lại?", answer: "Có. AI hỗ trợ rà soát sơ bộ, giải thích và gợi ý chỉnh sửa. Bạn cần kiểm tra điều khoản, nguồn tham chiếu và tham khảo chuyên gia pháp lý khi cần trước khi quyết định." },
  { question: "Hạn mức được chia sẻ thế nào?", answer: "Hạn mức dự kiến được dùng chung cho các thành viên trong doanh nghiệp theo gói dịch vụ. Chi tiết hạn mức sẽ được công bố khi mở đăng ký." },
];

export function FAQSection() {
  return <section id="cau-hoi" className="[&_h2]:text-[length:36px] [&_h2]:leading-[1.13] [&_h2]:tracking-[-1px] [&_h2]:font-[730] grid-cols-[1fr_1.7fr] pt-[60px] pb-[52px] [@media_(max-width:_900px)]:grid-cols-[1fr_1.4fr] [@media_(max-width:_900px)]:gap-6 [&_h2]:[@media_(max-width:_600px)]:text-[length:31px] [@media_(max-width:_600px)]:grid-cols-[1fr] [@media_(max-width:_600px)]:pb-8 w-[min(1380px,calc(100%_-_112px))] [margin-inline:auto] [@media_(max-width:_1199px)]:w-[calc(100%_-_64px)] [@media_(max-width:_600px)]:w-[calc(100%_-_40px)] grid gap-10" aria-labelledby="faq-heading"><div><p className="flex gap-[11px] items-center text-[#7382a5] text-[length:11px] font-semibold uppercase tracking-[1.8px] mb-4 before:content-[''] before:w-5 before:h-0.5 before:[background:var(--ls-blue)] text-[#bbc7db] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:tracking-[1.2px]">08 / Câu hỏi thường gặp</p><h2 id="faq-heading">Một vài điều<br />bạn muốn biết.</h2><p className="text-[length:16px] text-[color:var(--ls-muted)] mt-3.5 [@media_(max-width:_600px)]:text-[length:14px]">Những câu hỏi thường gặp về<br />cách LawScan hoạt động.</p></div><div className="[&_details]:[border-top:1px_solid_var(--ls-line)] [&_details]:px-0 [&_details]:py-3 [&_details]:last:[border-bottom:1px_solid_var(--ls-line)] [&_summary]:flex [&_summary]:items-center [&_summary]:justify-between [&_summary]:gap-4 [&_summary]:text-[length:15px] [&_summary]:font-semibold [&_summary]:[list-style:none] [&_summary]:min-h-6 [&_summary::-webkit-details-marker]:hidden [&_summary_span]:w-3.5 [&_summary_span]:h-3.5 [&_summary_span]:relative [&_summary_span]:shrink-0 [&_summary_span]:mr-1 [&_summary_span::before]:content-[''] [&_summary_span::before]:absolute [&_summary_span::before]:w-3 [&_summary_span::before]:h-[1.5px] [&_summary_span::before]:[background:#526587] [&_summary_span::before]:left-px [&_summary_span::before]:top-1.5 [&_summary_span::after]:content-[''] [&_summary_span::after]:absolute [&_summary_span::after]:w-3 [&_summary_span::after]:h-[1.5px] [&_summary_span::after]:[background:#526587] [&_summary_span::after]:left-px [&_summary_span::after]:top-1.5 [&_summary_span::after]:[transform:rotate(90deg)] [&_details[open]_summary_span::after]:hidden [&_details[open]_summary_span::before]:[background:var(--ls-blue)] [&_details_p]:text-[length:14px] [&_details_p]:text-[color:var(--ls-muted)] [&_details_p]:mt-2 [&_details_p]:pr-[25px] [&_summary]:[@media_(max-width:_600px)]:text-[length:14px] [&_summary]:[@media_(max-width:_600px)]:min-h-7">{questions.map((item, index) => <details key={item.question} name="lawscan-faq" open={index === 0}><summary>{item.question}<span aria-hidden="true" /></summary><p>{item.answer}</p></details>)}</div></section>;
}
