import { Icon } from "@/components/ui/icon";

const features = [
  { title: "Hiểu nội dung", icon: "document", description: "Trích xuất văn bản, tóm tắt điều khoản và nêu rõ ý chính bằng ngôn ngữ dễ hiểu." },
  { title: "Nhận diện rủi ro", icon: "search", description: "Phát hiện điều khoản chưa rõ ràng hoặc có rủi ro, kèm gợi ý chỉnh sửa." },
  { title: "Xem căn cứ", icon: "scales", description: "Giải thích kèm nguồn tham chiếu để bạn kiểm tra và có thêm góc nhìn." },
] as const;

export function FeaturesSection() {
  return (
    <section id="tinh-nang" className="grid-cols-[2.15fr_1fr] gap-14 pt-12 [&_h2]:text-[length:clamp(32px,3.4vw,49px)] [&_h2]:leading-[1.12] [&_h2]:font-[760] [&_h2]:tracking-[-1.8px] [@media_(max-width:_1199px)]:gap-[30px] [@media_(max-width:_900px)]:grid-cols-[1fr] [&_h2]:[@media_(max-width:_900px)]:text-[length:44px] [@media_(max-width:_600px)]:gap-[5px] [@media_(max-width:_600px)]:pt-[30px] [&_h2]:[@media_(max-width:_600px)]:text-[length:32px] [&_h2]:[@media_(max-width:_600px)]:tracking-[-1.2px] w-[min(1380px,calc(100%_-_112px))] [margin-inline:auto] [@media_(max-width:_1199px)]:w-[calc(100%_-_64px)] [@media_(max-width:_600px)]:w-[calc(100%_-_40px)] grid" aria-labelledby="features-heading">
      <div className="min-w-0">
        <p className="flex gap-[11px] items-center text-[#7382a5] text-[length:11px] font-semibold uppercase tracking-[1.8px] mb-4 before:content-[''] before:w-5 before:h-0.5 before:[background:var(--ls-blue)] text-[#bbc7db] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:tracking-[1.2px]">01 / Khám phá LawScan</p>
        <h2 id="features-heading">Điều khoản rõ hơn.<br />Quyết định chủ động hơn.</h2>
        <p className="text-[length:16px] text-[color:var(--ls-muted)] mt-3.5 [@media_(max-width:_600px)]:text-[length:14px]">Hiểu đúng nội dung, phát hiện rủi ro và xem căn cứ pháp lý<br className="hidden xl:block" /> dễ dàng — để bạn luôn nắm thế chủ động trong mọi quyết định.</p>
        <div className="relative h-[390px] overflow-hidden [background:radial-gradient(ellipse_at_55%_65%,#dfe6ec_0,#f3f6f8_45%,transparent_74%)] mt-1 [@media_(max-width:_600px)]:h-[300px] [@media_(max-width:_600px)]:[margin-inline:-20px]" role="img" aria-label="Minh họa một hợp đồng với điều khoản gia hạn chưa cụ thể được đánh dấu">
          <div className="w-[50px] h-[110px] [background:#688443] [filter:blur(7px)] absolute [transform:rotate(-25deg)] shadow-[5px_-120px_0_#7c985d] opacity-60 rounded-[100%_0] -left-7 top-[125px]" aria-hidden="true" />
          <div className="absolute w-[70%] min-h-[380px] [background:linear-gradient(120deg,#fff,#f2f4f7)] shadow-[2px_4px_8px_#25345110,12px_24px_40px_#2534512b] [transform:rotate(-15deg)] text-[length:13px] p-[42px] left-[10%] top-16 [&_h3]:font-bold [&_h3]:mx-0 [&_h3]:my-2 [&_p]:text-[#5a647d] [&_mark]:block [&_mark]:[background:#fff0cc] [&_mark]:[margin-block:8px_20px] [&_mark]:leading-normal [&_mark]:text-[#5a4829] [&_mark]:p-[7px] [@media_(max-width:_1199px)]:p-[26px] [@media_(max-width:_600px)]:w-[74%] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:min-h-[290px] [@media_(max-width:_600px)]:p-5 [@media_(max-width:_600px)]:left-[8%] [@media_(max-width:_600px)]:top-16 [transform:rotate(18deg)] [background:#eef2f6] left-[13%] top-[67px]" aria-hidden="true" />
          <div className="absolute w-[70%] min-h-[380px] [background:linear-gradient(120deg,#fff,#f2f4f7)] shadow-[2px_4px_8px_#25345110,12px_24px_40px_#2534512b] [transform:rotate(-15deg)] text-[length:13px] p-[42px] left-[10%] top-16 [&_h3]:font-bold [&_h3]:mx-0 [&_h3]:my-2 [&_p]:text-[#5a647d] [&_mark]:block [&_mark]:[background:#fff0cc] [&_mark]:[margin-block:8px_20px] [&_mark]:leading-normal [&_mark]:text-[#5a4829] [&_mark]:p-[7px] [@media_(max-width:_1199px)]:p-[26px] [@media_(max-width:_600px)]:w-[74%] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:min-h-[290px] [@media_(max-width:_600px)]:p-5 [@media_(max-width:_600px)]:left-[8%] [@media_(max-width:_600px)]:top-16"><h3>Điều 4. Thời hạn hợp đồng</h3><p>Hợp đồng có hiệu lực từ ngày ký và kéo dài đến khi các bên hoàn thành nghĩa vụ theo thỏa thuận.</p><mark>Việc gia hạn (nếu có) sẽ được hai bên thỏa thuận bằng văn bản vào thời điểm phù hợp.</mark><h3>Điều 5. Giá trị hợp đồng</h3><p>Tổng giá trị hợp đồng được hai bên thống nhất theo phụ lục đính kèm. Các khoản thanh toán sẽ được thực hiện theo tiến độ công việc.</p><span>···</span></div>
          <div className="absolute flex gap-[9px] w-[32%] [background:white] border shadow-[0_4px_8px_#263b610a,0_18px_32px_#263b612b] p-3.5 rounded-[10px] border-solid border-[#d3e1f4] right-[2%] top-[102px] before:content-[''] before:w-[43px] before:h-0.5 before:[background:#0066ff] before:absolute before:[transform:rotate(-35deg)] before:origin-right before:right-full before:top-[52%] [&_strong]:text-[length:11px] [&_p]:text-[length:10px] [&_p]:leading-normal [&_p]:text-[color:var(--ls-muted)] [&_p]:mt-[3px] [@media_(max-width:_600px)]:w-[39%] [@media_(max-width:_600px)]:gap-[5px] [@media_(max-width:_600px)]:p-[9px] [@media_(max-width:_600px)]:right-[3%] [@media_(max-width:_600px)]:top-[104px] [&_strong]:[@media_(max-width:_600px)]:text-[length:9px] [&_p]:[@media_(max-width:_600px)]:text-[length:8px]"><span className="inline-flex shrink-0 justify-center items-center w-4 h-4 text-[white] text-[length:12px] [background:#ffb400] mt-1 rounded-[50%] border-2 border-solid border-[#ffe097] [@media_(max-width:_600px)]:w-2.5 [@media_(max-width:_600px)]:h-2.5 [@media_(max-width:_600px)]:w-[13px] [@media_(max-width:_600px)]:h-[13px] [@media_(max-width:_600px)]:text-[length:9px]">!</span><div><strong>Thời hạn chưa cụ thể</strong><p>Điều khoản chưa nêu rõ thời điểm, điều kiện hoặc thời hạn gia hạn. Nên làm rõ để tránh rủi ro phát sinh khi thực hiện.</p></div></div>
          <span className="absolute text-[length:11px] text-[color:var(--ls-muted)] right-[11%] bottom-3.5">Ví dụ minh họa</span>
        </div>
      </div>
      <ol className="pt-6 [&_li]:relative [&_li]:grid [&_li]:grid-cols-[48px_1fr] [&_li]:gap-[23px] [&_li]:[border-bottom:1px_solid_var(--ls-line)] [&_li]:pt-10 [&_li]:pb-[35px] [&_li]:px-0 [&_li]:last:[border-bottom:0] [&_h3]:text-[length:21px] [&_h3]:font-[650] [&_h3]:tracking-[-0.5px] [&_h3]:mb-3 [&_li:first-child_h3]:[border-bottom:3px_solid_var(--ls-blue)] [&_li:first-child_h3]:pb-2.5 [&_p]:text-[color:var(--ls-muted)] [&_p]:text-[length:14px] [&_li]:[@media_(max-width:_1199px)]:gap-2.5 [&_h3]:[@media_(max-width:_1199px)]:text-[length:18px] [@media_(max-width:_900px)]:grid [@media_(max-width:_900px)]:grid-cols-[repeat(3,1fr)] [@media_(max-width:_900px)]:gap-[22px] [@media_(max-width:_900px)]:pt-0 [@media_(max-width:_900px)]:pb-9 [@media_(max-width:_900px)]:px-0 [&_li]:[@media_(max-width:_900px)]:block [&_li]:[@media_(max-width:_900px)]:[border-bottom:0] [&_li]:[@media_(max-width:_900px)]:pb-0 [&_svg]:[@media_(max-width:_900px)]:mb-[15px] [&_li:first-child_h3]:[@media_(max-width:_900px)]:[border-bottom:0] [&_li:first-child_h3]:[@media_(max-width:_900px)]:pb-0 [@media_(max-width:_600px)]:grid-cols-[1fr] [@media_(max-width:_600px)]:gap-0 [@media_(max-width:_600px)]:pb-[30px] [&_li]:[@media_(max-width:_600px)]:grid [&_li]:[@media_(max-width:_600px)]:grid-cols-[42px_1fr] [&_li]:[@media_(max-width:_600px)]:gap-5 [&_li]:[@media_(max-width:_600px)]:[border-bottom:1px_solid_var(--ls-line)] [&_li]:[@media_(max-width:_600px)]:pt-[30px] [&_li]:[@media_(max-width:_600px)]:pb-5 [&_li]:[@media_(max-width:_600px)]:px-0 [&_svg]:[@media_(max-width:_600px)]:w-[30px] [&_svg]:[@media_(max-width:_600px)]:mt-3.5 [&_h3]:[@media_(max-width:_600px)]:mb-1.5">{features.map((feature, index) => <li key={feature.title}><span className="absolute text-[length:18px] font-[650] text-[color:var(--ls-blue)] left-0 top-1 [@media_(max-width:_600px)]:text-[length:14px] [@media_(max-width:_600px)]:top-[5px]">0{index + 1}</span><Icon name={feature.icon} width="40" height="40" /><div><h3>{feature.title}</h3><p>{feature.description}</p></div></li>)}</ol>
    </section>
  );
}
