import { Icon } from "@/components/ui/icon";
import { ContractDemo } from "./contract-demo";

export function HeroSection() {
  return (
    <section className="relative [background:radial-gradient(ellipse_at_82%_35%,#dceaff_0,transparent_57%),linear-gradient(110deg,#f7f9fd_8%,#eef4fc_100%)] [border-block:1px_solid_#e5edf8]" aria-labelledby="hero-heading">
      <div className="grid-cols-[0.83fr_1.17fr] gap-11 pt-[30px] pb-[42px] [&_h1]:[font-family:var(--font-geist-sans),sans-serif] [&_h1]:text-[length:clamp(56px,6.1vw,90px)] [&_h1]:font-[770] [&_h1]:leading-[1.02] [&_h1]:tracking-[-0.057em] [@media_(max-width:_1199px)]:gap-[26px] [@media_(max-width:_1199px)]:grid-cols-[0.9fr_1.1fr] [&_h1]:[@media_(max-width:_1199px)]:text-[length:65px] [&_h1]:[@media_(max-width:_1199px)]:tracking-[-3px] [@media_(max-width:_900px)]:grid-cols-[1fr] [@media_(max-width:_900px)]:gap-4 [@media_(max-width:_900px)]:pt-2.5 [&_h1]:[@media_(max-width:_900px)]:text-[length:80px] [&_h1]:[@media_(max-width:_600px)]:text-[length:clamp(45px,11vw,66px)] [&_h1]:[@media_(max-width:_600px)]:tracking-[-2.5px] [&_h1]:[@media_(max-width:_600px)]:leading-[1.1] [@media_(max-width:_600px)]:pb-7 w-[min(1380px,calc(100%_-_112px))] [margin-inline:auto] [@media_(max-width:_1199px)]:w-[calc(100%_-_64px)] [@media_(max-width:_600px)]:w-[calc(100%_-_40px)] grid items-center">
      <div className="[padding-block:36px_24px] [@media_(max-width:_900px)]:max-w-screen-sm [@media_(max-width:_600px)]:pt-5">
        <p className="inline-flex items-center gap-[9px] text-[#075bd6] [background:#e6efff] border [font-family:var(--font-geist-mono),var(--font-geist-sans),sans-serif] uppercase font-[590] tracking-[1.45px] text-[length:11px] mb-[22px] px-3 py-[7px] rounded-[30px] border-solid border-[#ccdfff] before:content-[''] before:w-1.5 before:h-1.5 before:shrink-0 before:[background:#0066ff] before:shadow-[0_0_0_3px_#0066ff0d] before:rounded-[50%] [@media_(max-width:_1199px)]:text-[length:11px] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:tracking-[0.8px] [@media_(max-width:_600px)]:mb-[18px]">Trợ lý rà soát hợp đồng.</p>
        <h1 id="hero-heading">Nhìn rõ rủi ro.<br />Trước khi<br /><span className="relative inline-block text-[color:var(--ls-blue)] [font-family:var(--font-lora),Georgia,serif] text-[length:1.07em] italic font-[650] tracking-[-0.065em] pl-[0.01em] pr-[0.1em] pt-[0.03em] pb-[0.11em] after:content-[''] after:absolute after:h-[0.11em] after:[border-top:0.045em_solid_#1477ff] after:[transform:rotate(-2deg)] after:opacity-[0.88] after:rounded-[50%] after:left-[4%] after:right-[1%] after:bottom-[0.04em]">bạn ký.</span></h1>
        <p className="text-[length:clamp(19px,1.65vw,25px)] leading-normal text-[#3d4b70] max-w-[530px] mt-[30px] [@media_(max-width:_1199px)]:text-[length:20px] [@media_(max-width:_900px)]:max-w-[560px] [@media_(max-width:_600px)]:text-[length:18px] [@media_(max-width:_600px)]:mt-[22px]">Mỗi cảnh báo quay về đúng điều khoản, kèm lý do và nguồn cần đối chiếu để bạn chủ động quyết định.</p>
        <div className="mt-8 [@media_(max-width:_1199px)]:gap-[18px] [@media_(max-width:_600px)]:gap-[17px] [@media_(max-width:_600px)]:mt-6 flex flex-wrap items-center gap-6"><a className="inline-flex justify-center items-center gap-[15px] min-h-[52px] [background:var(--ls-blue)] text-[white] border border-[color:var(--ls-blue)] font-[550] text-center [text-decoration:none] [transition:background-color_0.2s,color_0.2s,border-color_0.2s,box-shadow_0.25s,transform_0.25s] px-[25px] py-3 rounded-[9px] border-solid hover:text-[white] hover:[background:#0054d4] hover:[transform:translateY(-1px)] hover:border-[#0054d4] min-w-[124px] rounded-[13px] min-h-16 text-[length:19px] py-4 rounded-xl [@media_(hover:_hover)_and_(pointer:_fine)]:hover:[transform:translateY(-3px)] [@media_(hover:_hover)_and_(pointer:_fine)]:hover:shadow-[0_10px_24px_-10px_#0066ff80] [@media_(max-width:_1199px)]:text-[length:16px] [@media_(max-width:_1199px)]:[padding-inline:18px] [@media_(max-width:_1199px)]:min-h-[54px] [@media_(max-width:_600px)]:text-[length:16px] [@media_(max-width:_600px)]:text-[length:14px] [@media_(max-width:_600px)]:mt-2 motion-reduce:hover:transform-none" href="#kiem-tra-dieu-khoan">Thử một điều khoản <Icon name="arrow" /></a><a className="text-[color:var(--ls-blue)] text-[length:17px] [@media_(max-width:_600px)]:text-[length:14px]" href="#quy-trinh">Khám phá LawScan.</a></div>
        <ul className="mt-[30px] [&_li]:[background:#ffffffb3] [&_li]:border [&_li]:text-[length:13px] [&_li]:px-[17px] [&_li]:py-[7px] [&_li]:rounded-[30px] [&_li]:border-solid [&_li]:border-[#dce6f2] [@media_(max-width:_600px)]:gap-2 [@media_(max-width:_600px)]:mt-[23px] [&_li]:[@media_(max-width:_600px)]:text-[length:12px] [&_li]:[@media_(max-width:_600px)]:px-3.5 [&_li]:[@media_(max-width:_600px)]:py-1.5 flex flex-wrap gap-3" aria-label="Phạm vi hỗ trợ"><li>Tiếng Việt</li><li>Mua bán</li><li>Dịch vụ</li></ul>
      </div>
      <ContractDemo />
      </div>
    </section>
  );
}
