const steps = [
  { number: "01", title: "Tải hợp đồng", description: "Hỗ trợ các định dạng phổ biến." },
  { number: "02", title: "Xem phân tích", description: "Phát hiện rủi ro, điểm cần làm rõ." },
  { number: "03", title: "Kiểm tra và xuất báo cáo", description: "Tổng hợp rõ ràng, dễ chia sẻ." },
];

export function HowItWorksSection() {
  return <section id="quy-trinh" className="[padding-block:42px_46px] [&_h2]:text-[length:30px] [&_h2]:tracking-[-0.8px] [&_h2]:leading-[1.3] [&_h2]:font-bold [&_h2]:[@media_(max-width:_900px)]:text-[length:26px] [@media_(max-width:_600px)]:[padding-block:26px_32px] [&_h2]:[@media_(max-width:_600px)]:text-[length:25px] w-[min(1380px,calc(100%_-_112px))] [margin-inline:auto] [@media_(max-width:_1199px)]:w-[calc(100%_-_64px)] [@media_(max-width:_600px)]:w-[calc(100%_-_40px)]" aria-labelledby="how-heading"><h2 id="how-heading">Một quy trình rõ ràng, từ đầu đến cuối.</h2><ol className="mt-8 [&_li]:relative [&_h3]:text-[length:18px] [&_h3]:font-[650] [&_p]:text-[color:var(--ls-muted)] [&_p]:text-[length:15px] [&_p]:mt-1 [&_li:not(:last-child)]:xl:after:content-[''] [&_li:not(:last-child)]:xl:after:absolute [&_li:not(:last-child)]:xl:after:w-[60px] [&_li:not(:last-child)]:xl:after:h-px [&_li:not(:last-child)]:xl:after:[background:#c9d8ec] [&_li:not(:last-child)]:xl:after:right-3 [&_li:not(:last-child)]:xl:after:top-[22px] [&_li]:[@media_(max-width:_900px)]:gap-3.5 [&_h3]:[@media_(max-width:_900px)]:text-[length:16px] [&_p]:[@media_(max-width:_900px)]:text-[length:13px] [@media_(max-width:_600px)]:gap-[23px] [@media_(max-width:_600px)]:mt-[25px] [&_h3]:[@media_(max-width:_600px)]:text-[length:17px] [&_p]:[@media_(max-width:_600px)]:text-[length:14px] grid gap-8 md:grid-cols-3">{steps.map(step => <li key={step.number} className="flex items-start gap-6"><span className="text-[color:var(--ls-blue)] text-[length:46px] leading-[1.1] font-[650] tracking-[-2px] [@media_(max-width:_900px)]:text-[length:36px] [@media_(max-width:_600px)]:min-w-[50px] [@media_(max-width:_600px)]:text-[length:39px]">{step.number}</span><div><h3>{step.title}</h3><p>{step.description}</p></div></li>)}</ol></section>;
}
