import { Icon } from "@/components/ui/icon";

const cases = [
  { icon: "briefcase", role: "Chủ doanh nghiệp", title: "Nắm nhanh điều cần quyết định", text: "Xem nghĩa vụ, thời hạn và các điểm cần hỏi lại trước khi đồng ý với đối tác.", items: ["Tóm tắt nội dung chính", "Ưu tiên rủi ro cần xử lý"] },
  { icon: "user", role: "Người quản lý", title: "Theo dõi cam kết thực hiện", text: "Kiểm tra phạm vi công việc, thanh toán, nghiệm thu và điều kiện chấm dứt.", items: ["Đối chiếu trách nhiệm hai bên", "Chia sẻ báo cáo cho đội ngũ"] },
  { icon: "scales", role: "Nhân sự pháp chế", title: "Có điểm bắt đầu để rà soát", text: "Tổng hợp sơ bộ các vấn đề, nguồn tham chiếu và lịch sử chỉnh sửa trong một nơi.", items: ["Xem lại từng nhận định", "Ghi nhận quyết định cuối cùng"] },
] as const;

export function UseCasesSection() {
  return (
    <section id="doi-tuong" className="px-0 py-[100px] [@media_(max-width:_900px)]:[padding-block:70px] [@media_(max-width:_600px)]:[padding-block:56px]" aria-labelledby="use-case-heading">
      <div className="w-[min(1380px,calc(100%_-_112px))] [margin-inline:auto] [@media_(max-width:_1199px)]:w-[calc(100%_-_64px)] [@media_(max-width:_600px)]:w-[calc(100%_-_40px)]">
        <div className="[&_h2]:text-[length:clamp(36px,4vw,55px)] [&_h2]:leading-[1.12] [&_h2]:tracking-[-2px] [&_h2]:font-[730] [&_h2_span]:text-[#697891] [&>_p]:text-[#60708b] [&>_p]:text-[length:17px] [&>_p]:mt-[18px] flex [align-items:end] justify-between gap-[60px] [&>_p]:max-w-[460px] [&>_p]:mt-0 [&>_p]:mb-1.5 [&>_p]:mx-0 [@media_(max-width:_900px)]:[align-items:start] [@media_(max-width:_900px)]:flex-col [@media_(max-width:_900px)]:gap-5 [&_h2]:[@media_(max-width:_600px)]:text-[length:32px] [&_h2]:[@media_(max-width:_600px)]:tracking-[-1.2px] [&>_p]:[@media_(max-width:_600px)]:text-[length:14px]" data-reveal><div><p className="flex gap-[11px] items-center text-[#7382a5] text-[length:11px] font-semibold uppercase tracking-[1.8px] mb-4 before:content-[''] before:w-5 before:h-0.5 before:[background:var(--ls-blue)] text-[#bbc7db] [@media_(max-width:_600px)]:text-[length:10px] [@media_(max-width:_600px)]:tracking-[1.2px]">04 / Dành cho đội ngũ</p><h2 id="use-case-heading">Mỗi vai trò một góc nhìn.<br /><span>Cùng một nguồn thông tin.</span></h2></div><p>LawScan giúp các bên trao đổi trên cùng nội dung hợp đồng và ghi nhận rõ điều cần xử lý.</p></div>
        <div className="grid grid-cols-[repeat(3,1fr)] gap-5 mt-12 [@media_(max-width:_900px)]:grid-cols-[1fr] [@media_(max-width:_900px)]:max-w-[620px] [@media_(max-width:_600px)]:mt-8">{cases.map((item, index) => <article key={item.role} className="relative border [background:#fff] overflow-hidden [transition:transform_0.25s,border-color_0.25s,box-shadow_0.25s] p-[31px] rounded-[18px] border-solid border-[#dde5ef] before:content-[''] before:absolute before:w-[130px] before:h-[130px] before:[background:#e7f1ff] before:right-[-62px] before:top-[-68px] before:transition-transform before:duration-[0.35s] before:ease-[ease] before:delay-0 before:rounded-[50%] [&_h3]:text-[length:22px] [&_h3]:leading-[1.3] [&_h3]:tracking-[-0.6px] [&_h3]:mt-[7px] [&>_p]:text-[#61708a] [&>_p]:text-[length:14px] [&>_p]:leading-[1.7] [&>_p]:mt-3 [&_ul]:grid [&_ul]:gap-2.5 [&_ul]:[border-top:1px_solid_#e6ebf2] [&_ul]:mt-[21px] [&_ul]:pt-5 [&_li]:flex [&_li]:gap-[9px] [&_li]:items-center [&_li]:text-[#4f6079] [&_li]:text-[length:12px] [&_li_svg]:w-[15px] [&_li_svg]:text-[#0066ff] [@media_(hover:_hover)_and_(pointer:_fine)]:hover:[transform:translateY(-5px)] [@media_(hover:_hover)_and_(pointer:_fine)]:hover:shadow-[0_22px_45px_-30px_#123a7055] [@media_(hover:_hover)_and_(pointer:_fine)]:hover:border-[#b7d2fa] [@media_(hover:_hover)_and_(pointer:_fine)]:hover:before:[transform:scale(1.15)] [@media_(max-width:_600px)]:p-[25px] motion-reduce:transition-none before:motion-reduce:transition-none hover:motion-reduce:transform-none" data-reveal data-reveal-delay={index * 80}><span className="grid place-items-center w-12 h-12 text-[#0066ff] [background:#edf5ff] rounded-[13px] [&_svg]:w-6"><Icon name={item.icon} /></span><p className="!text-[#0066ff] !text-[length:11px] !mt-7 font-[650] uppercase tracking-[1.3px]">{item.role}</p><h3>{item.title}</h3><p>{item.text}</p><ul>{item.items.map(value => <li key={value}><Icon name="check" />{value}</li>)}</ul></article>)}</div>
      </div>
    </section>
  );
}
